materias_por_nivel = {
    "Nivel A": ["INGLES I", "FISICA GENERAL", "ALGEBRA I", "CALCULO I", "INTRODUCCION A LA PROGRAMACION"],
    "Nivel B": ["INGLES II", "ALGEBRA II", "CALCULO II", "ELEM. DE PROGRAMACION Y ESTRUC. DE DATOS", "ARQUITECTURA DE COMPUTADORAS I", "PROGRAMACION"],
    "Nivel C": ["CALCULO NUMERICO", "LOGICA", "ARQUITECTURA DE COMPUTADORAS II", "TEORIA DE GRAFOS", "ORGANIZACION Y METODOS", "METODOS Y TECNICAS DE PROGRAMACION"],
    "Nivel D": ["PROBABILIDAD Y ESTADISTICA", "TALLER DE PROGRAMACION EN BAJO NIVEL", "BASE DE DATOS I", "SISTEMAS DE INFORMACION I", "PROGRAMACION FUNCIONAL", "ALGORITMOS AVANZADOS"],
    "Nivel E": ["BASE DE DATOS II", "TALLER DE SISTEMAS OPERATIVOS", "SISTEMAS DE INFORMACION II", "TEORIA DE AUTOMATAS Y LENG. FORMALES", "GRAFICACION POR COMPUTADORA", "INTELIGENCIA ARTIFICIAL I"],
    "Nivel F": ["INGENIERIA DE SOFTWARE", "REDES DE COMPUTADORAS", "ESTRUCTURA Y SEMANTICA DE LENGUAJES DE PROGRA", "TALLER DE BASE DE DATOS", "INTELIGENCIA ARTIFICIAL II", "PROGRAMACION WEB"],
    "Nivel G": ["SIMULACION DE SISTEMAS", "TALLER DE INGENIERIA DE SOFTWARE", "ARQUITECTURA DE SOFTWARE", "TELEFONIA IP", "INTERACCION HUMANO COMPUTADOR", "TECNOLOGIA REDES AVANZADAS"],
    "Nivel H": ["GENERACION DE SOFTWARE", "APLICACION DE SISTEMAS OPERATIVOS", "EVALUACION Y AUDITORIA DE SISTEMAS", "TALLER DE GRADO I"],
    "Nivel I": ["PROCESOS AGILES", "WEB SEMANTICAS", "ROBOTICA", "PROGRAMACION MOVIL", "SEGURIDAD DE SISTEMAS", "TALLER DE GRADO II", "BUSINESS INTELLIGENCE Y BIG DATA"]
}

def obtener_materias_por_semestre(semestre):
    return materias_por_nivel.get(semestre, [])